//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Web04.Core.Resources.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Web04.Core.Resources.Account.AccountVN", typeof(AccountVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản.
        /// </summary>
        public static string ACCOUNT_CODE {
            get {
                return ResourceManager.GetString("ACCOUNT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diễn giải.
        /// </summary>
        public static string ACCOUNT_DESCRIPTION {
            get {
                return ResourceManager.GetString("ACCOUNT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tiếng anh.
        /// </summary>
        public static string ACCOUNT_ENGLISH_NAME {
            get {
                return ResourceManager.GetString("ACCOUNT_ENGLISH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản.
        /// </summary>
        public static string ACCOUNT_NAME {
            get {
                return ResourceManager.GetString("ACCOUNT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính chất.
        /// </summary>
        public static string ACCOUNT_NATURE {
            get {
                return ResourceManager.GetString("ACCOUNT_NATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string ACCOUNT_STATUS {
            get {
                return ResourceManager.GetString("ACCOUNT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương tính.
        /// </summary>
        public static string BOTH {
            get {
                return ResourceManager.GetString("BOTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản &lt;{0}&gt;   đang ở trạng thái &lt;Ngừng sử dụng&gt;. Bạn không được phép chọn thuộc tài khoản này..
        /// </summary>
        public static string CANT_CHOOSE_STOP {
            get {
                return ResourceManager.GetString("CANT_CHOOSE_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản &lt;{0}&gt; đang ở trạng thái &lt;Ngừng sử dụng&gt;. Bạn không thể thiết lập trạng thái \&quot;Sử dụng\&quot; cho &lt;{1}&gt; con..
        /// </summary>
        public static string CANT_CHOOSE_STOP_FOR_CHILD {
            get {
                return ResourceManager.GetString("CANT_CHOOSE_STOP_FOR_CHILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa không thành công. Không thể sửa danh mục cha..
        /// </summary>
        public static string CHANGE_FAIL {
            get {
                return ResourceManager.GetString("CHANGE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dư nợ.
        /// </summary>
        public static string DEBT {
            get {
                return ResourceManager.GetString("DEBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa không thành công. Không thể xóa danh mục cha khi chưa xóa con..
        /// </summary>
        public static string DELETE_FAIL {
            get {
                return ResourceManager.GetString("DELETE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dư có.
        /// </summary>
        public static string EXCESS {
            get {
                return ResourceManager.GetString("EXCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản &lt;{0}&gt; đã tồn tại.
        /// </summary>
        public static string EXISTED_ACCOUNT_CODE {
            get {
                return ResourceManager.GetString("EXISTED_ACCOUNT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã {0} đã tồn tại..
        /// </summary>
        public static string EXISTED_CODE {
            get {
                return ResourceManager.GetString("EXISTED_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản không hợp lệ. Số tài khoản chi tiết phải bắt đầu bằng số tài khoản tổng hợp.
        /// </summary>
        public static string NEED_STARTWITH_PARENTCODE {
            get {
                return ResourceManager.GetString("NEED_STARTWITH_PARENTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có số dư.
        /// </summary>
        public static string NO_BALANCE {
            get {
                return ResourceManager.GetString("NO_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa không thành công. Tài khoản đã có phát sinh trên các danh mục, chứng từ..
        /// </summary>
        public static string NO_DELETE {
            get {
                return ResourceManager.GetString("NO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản tổng hợp không tồn tại.
        /// </summary>
        public static string NO_EXIST_PARENT {
            get {
                return ResourceManager.GetString("NO_EXIST_PARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy.
        /// </summary>
        public static string NOT_FOUND {
            get {
                return ResourceManager.GetString("NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản có phần đầu &lt;{0}&gt; trùng với tài khoản con cùng cấp &lt;{1}&gt; ..
        /// </summary>
        public static string NOT_START_WITH_FAIL {
            get {
                return ResourceManager.GetString("NOT_START_WITH_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string ORDER {
            get {
                return ResourceManager.GetString("ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách hệ thống tài khoản.
        /// </summary>
        public static string SHEET_NAME {
            get {
                return ResourceManager.GetString("SHEET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngừng sử dụng.
        /// </summary>
        public static string STOP {
            get {
                return ResourceManager.GetString("STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sử dụng.
        /// </summary>
        public static string USE {
            get {
                return ResourceManager.GetString("USE", resourceCulture);
            }
        }
    }
}
